version: '3.8'

services:
  backend:
    build:
      context: ./backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    command: npm start

  frontend:
    build:
      context: ./frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm start

# Nếu cần thêm database (ví dụ: MongoDB, MySQL), có thể bổ sung thêm service ở đây
